GROUP_A_BRANDS = [
    {"brand": "EXM", "brand_name": "Exium"},
    {"brand": "EMP", "brand_name": "Exium Mups"},
    {"brand": "COR", "brand_name": "Coralcal-D"},
    {"brand": "CDX", "brand_name": "Coralcal-DX"},
    {"brand": "CVT", "brand_name": "Coralcal Vita"},
    {"brand": "RIV", "brand_name": "Rivotril"},
    {"brand": "RAV", "brand_name": "Rofuclav"},
    {"brand": "NCB", "brand_name": "Neucos-B"},
    {"brand": "NAP", "brand_name": "Naprosyn"},
    {"brand": "NPS", "brand_name": "Naprosyn-Plus"},
    {"brand": "ATZ", "brand_name": "ATOZ"},
    {"brand": "ATA", "brand_name": "Acteria"},
    {"brand": "ROX", "brand_name": "Rofixim"},
    {"brand": "ROF", "brand_name": "Rofecin"},
    {"brand": "TOR", "brand_name": "Toradolin"},
    {"brand": "MRL", "brand_name": "Merocil"},
    {"brand": "SKV", "brand_name": "SmofKabiven"},
    {"brand": "GVD", "brand_name": "Gavirad"},
    {"brand": "EFD", "brand_name": "Efodio"},
    {"brand": "ACS", "brand_name": "Acos"},
    {"brand": "LIZ", "brand_name": "Lizid"},
    {"brand": "AVN", "brand_name": "Avenac"},
    {"brand": "RGL", "brand_name": "Radigel"},
    {"brand": "FAS", "brand_name": "Fastel"},
    {"brand": "ROU", "brand_name": "Rofurox"},
    {"brand": "AZF", "brand_name": "Azofend"},
    {"brand": "ANH", "brand_name": "Aminosteril-N Hepa 8%"},
    {"brand": "PFL", "brand_name": "Propofol"},
    {"brand": "EFZ", "brand_name": "Efitaz"},
    {"brand": "TFN", "brand_name": "Tinafin"},
    {"brand": "FLZ", "brand_name": "Feeliz"},
    {"brand": "NZN", "brand_name": "Nalzin"},
    {"brand": "IBT", "brand_name": "Inbuten"},
    {"brand": "RVT", "brand_name": "Radivit-C"},
    {"brand": "FAB", "brand_name": "Fabetor"},
    {"brand": "PMR", "brand_name": "Premarin"},
    {"brand": "INN", "brand_name": "Innocan"},
    {"brand": "OMG", "brand_name": "Omegaven"},
    {"brand": "VLT", "brand_name": "Volulyte"},
    {"brand": "RVD", "brand_name": "Radivit-D"},
    {"brand": "INT", "brand_name": "Inmit"},
    {"brand": "WIN", "brand_name": "Winbac"},
    {"brand": "ZNC", "brand_name": "Zinc-R"},
    {"brand": "APM", "brand_name": "Andepram"},
    {"brand": "TLP", "brand_name": "Tylen Plus"},
    {"brand": "ZIL", "brand_name": "Zilon"},
    {"brand": "DOL", "brand_name": "Dolceta"},
    {"brand": "ADX", "brand_name": "Algeum-DX"},
    {"brand": "LPS", "brand_name": "Lanplus"},
    {"brand": "ALG", "brand_name": "Algeum-D"},
    {"brand": "KBN", "brand_name": "Kabiven"}
]

GROUP_B_BRANDS = [
    {"brand": "PCA", "brand_name": "Prelica"},
    {"brand": "XFL", "brand_name": "Xyflo"},
    {"brand": "CTR", "brand_name": "Carticare"},
    {"brand": "VPN", "brand_name": "Vono"},
    {"brand": "TIB", "brand_name": "Tedibac"},
    {"brand": "EGL", "brand_name": "Eggcal"},
    {"brand": "FYL", "brand_name": "Fylox"},
    {"brand": "ZPN", "brand_name": "Zylopen"},
    {"brand": "RIL", "brand_name": "Raditil"},
    {"brand": "LAN", "brand_name": "Lexotanil"},
    {"brand": "XNB", "brand_name": "Xenobese"},
    {"brand": "ROA", "brand_name": "Roaccutane"},
    {"brand": "RTL", "brand_name": "Raditrol"},
    {"brand": "DMC", "brand_name": "Dormicum"},
    {"brand": "GNX", "brand_name": "Greenox"},
    {"brand": "BON", "brand_name": "Bonova"},
    {"brand": "CCK", "brand_name": "Coralcal-Kit"},
    {"brand": "RFA", "brand_name": "Refla"},
    {"brand": "TLC", "brand_name": "Tarlica"},
    {"brand": "FXT", "brand_name": "Fixtat"},
    {"brand": "UTI", "brand_name": "Utifos"},
    {"brand": "PMT", "brand_name": "Prompton"},
    {"brand": "LOA", "brand_name": "Lola"},
    {"brand": "XEL", "brand_name": "Xelcom"},
    {"brand": "MIN", "brand_name": "Minista"},
    {"brand": "BTN", "brand_name": "Backtone"},
    {"brand": "DST", "brand_name": "Dexochol"},
    {"brand": "NTX", "brand_name": "Natlax"},
    {"brand": "BTA", "brand_name": "Butasiv"},
    {"brand": "AFX", "brand_name": "Alafix"},
    {"brand": "PIM", "brand_name": "Pantium"},
    {"brand": "EXR", "brand_name": "Exler"},
    {"brand": "OBX", "brand_name": "Obexa"},
    {"brand": "AMB", "brand_name": "Ambryl"},
    {"brand": "FBU", "brand_name": "Febout"},
    {"brand": "BTV", "brand_name": "Bactovate"}
]

GROUP_C_BRANDS = [
    {"brand": "ARD", "brand_name": "Ardance"},
    {"brand": "DVS", "brand_name": "Duovas"},
    {"brand": "CRL", "brand_name": "Carlina"},
    {"brand": "CRV", "brand_name": "Creva"},
    {"brand": "ACK", "brand_name": "Accu-Chek"},
    {"brand": "RDM", "brand_name": "Radimet"},
    {"brand": "RDZ", "brand_name": "Radizid"},
    {"brand": "RDG", "brand_name": "Radiglip"},
    {"brand": "PLR", "brand_name": "Prelizer"},
    {"brand": "PDL", "brand_name": "Pidogrel"},
    {"brand": "TGL", "brand_name": "Triginal"},
    {"brand": "FRV", "brand_name": "Frenvas"},
    {"brand": "SVN", "brand_name": "Sevitan"},
    {"brand": "RDT", "brand_name": "Raditrend"},
    {"brand": "SPI", "brand_name": "Spilac"},
    {"brand": "CDL", "brand_name": "Cardicil"},
    {"brand": "MIC", "brand_name": "Micatel"}
]